<?php 
global $post;
$settings = new Wiredrive_Theme_Settings();
$fonts = $settings->getFonts();
$options = $settings->getOptions();
$pagetitle = get_post_meta($post->ID, 'pagetitle', true);
$menuPosition = $options['menu_position'];
?>
<style>
/* This is generated by the theme */
/* Page Styles */
    body {
        color: <?php echo $options['body_font_color'];?>;
        font-family: <?php 
        $font = $options['body_font'];
        echo($fonts[$font]['family']);
        ?>;
        <?php
        if (isset($fonts[$font]['weight'])) {
            echo 'font-weight: '.$fonts[$font]['weight'];
        }
        ?>;
        font-size: <?php echo $options['body_font_size'];?>px;
    } 
    #header-wrapper {
        background-color: <?php echo $options['header_color'];?>;
    }
    #container {
        background-color: <?php echo $options['container_color'];?>;
        margin: <?php echo $options['site_alignment'];?>;
    }
    #footer-wrapper {
        background-color: <?php echo $options['footer_color'];?>;
        color: <?php echo $options['footer_font_color'];?>;
    }

/* Links */
    a {
        color: <?php echo $options['link_font_color'];?>;
    }
    a:hover, .top.menu > li.active a {
        color: <?php echo $options['link_hover_font_color'];?>;
    }

/* Page Titles */
    .title h2, h2.post-title {
        display: <?php echo $options['page_titles'] ?>;
        font-family: <?php 
        $font = $options['title_font'];
        echo($fonts[$font]['family']);
        ?>;
        <?php
        if (isset($fonts[$font]['weight'])) {
            echo 'font-weight: '.$fonts[$font]['weight'];
        }
        ?>;
        font-size: <?php echo $options['title_font_size'];?>px;
    }
    
    <?php if ($pagetitle == 1) : ?>
    .title h2 {
        display: block;
    }
    <?php endif; ?>

/* Menus */
    <?php if($options['menu_functionality'] == 'block-menu') : ?>
        .nav ul.children, .top.menu .sub-menu {
            display: block;
        }
        .nav ul.children li a {
            padding-left: 0;
        }
    <?php endif; ?>

    .blog-nav a, .nav a, .nav .children a, .menu a {
        color: <?php echo $options['main_menu_font_color'];?>;
        font-family: <?php 
        $font = $options['menu_font'];
        echo($fonts[$font]['family']);
        ?>;
        <?php
        if (isset($fonts[$font]['weight'])) {
            echo 'font-weight: '.$fonts[$font]['weight'];
        }
        ?>;
        font-size: <?php echo $options['menu_font_size'];?>px;
    }
    .top.menu .sub-menu, .top.menu .children  {
        background-color: <?php echo $options['header_color'];?>;
    }
    .nav .children a, .nav .sub-menu a, .menu .children a, .menu .sub-menu a {
        color: <?php echo $options['sub_menu_font_color'];?>;
    }
    
/* Menu Alignment */
<?php if($menuPosition == 'left') : ?>
    .content, .pagepost {
        float: right;
        width: 720px;
    }
<?php else : ?>
    .content, .pagepost {
        float: left;
        width: 100%;
    }
    .content-wrapper {
        margin: 0 28px;
    }
<?php endif; ?>

/* Comments */
ul.commentlist > li {
    border-bottom: 1px solid <?php echo $options['body_font_color'];?>;
}

#comments, ul.commentlist ul.children li {
    border-top: 1px solid <?php echo $options['body_font_color'];?>;
}


/* Blog Styles */
.blog .post {
    border-top: 1px solid <?php echo $options['body_font_color'];?>;
}
</style>