<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Document sans titre</title>
<div id="bloc1">
  <p class="justifier">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla at tortor ut diam porttitor porta vel ac magna. Cras rutrum congue urna at hendrerit. Sed lectus nisl, elementum eget viverra vel, imperdiet sed leo. Nunc varius aliquet urna, in gravida mauris vehicula ut. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam quis mauris ac felis eleifend facilisis a eu velit. Maecenas massa lorem, vehicula non lobortis aliquam, vulputate vel sem. Curabitur quis nisl sit amet odio venenatis aliquet eget id leo. Quisque aliquam commodo metus, sit amet porta risus pulvinar sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque ornare eleifend sapien, ut malesuada purus ornare a. Fusce consequat gravida porttitor. Donec est leo, venenatis eleifend rhoncus non, sagittis viverra tellus. Proin molestie nisi vel libero suscipit vel laoreet elit congue. Donec ut dui ipsum, suscipit aliquam velit. Vivamus eget quam dui. Etiam vulputate urna at elit dapibus venenatis. Praesent id leo lectus, eu dignissim metus. Etiam suscipit faucibus arcu eget laoreet.</p>
  <p><span class="justifier">Ut gravida arcu eu arcu congue accumsan. Quisque vehicula pulvinar quam, eget tempor lorem bibendum sed. Nullam sed lacinia ante. Maecenas arcu lorem, varius non consectetur accumsan, mattis quis purus. Etiam quis egestas enim. Phasellus lacinia, ligula sagittis interdum dapibus, ligula elit congue neque, non tincidunt odio metus sit amet tellus. Proin rutrum ultrices nisl, nec pellentesque sapien viverra at. Aenean ultricies, libero id dapibus rutrum, nulla dolor interdum velit, sit amet pulvinar odio massa </span>euismod<span class="justifier">quam. Nullam cursus neque in justo sodales tincidunt. Vivamus eget lectus sem, at consectetur metus. Vestibulum elit odio, fringilla ut fermentum vel, fermentum et leo. Sed scelerisque pretium elit, ut pretium eros tincidunt eu. Integer a arcu neque. Nunc vitae dolor nec enim ornare aliquam. Etiam mi ipsum, posuere non viverra eu, molestie in nibh. Aliquam venenatis consectetur augue, vitae egestas tortor imperdiet eget. Vestibulum justo orci, commodo ut euismod ac, sagittis a lacus. Sed nec erat quis nisl adipiscing adipiscing et id odio. Pellentesque pellentesque volutpat sollicitudin.</span></p>
  <p class="justifier">Curabitur eget turpis eu ligula adipiscing lacinia vel eget nunc. In pretium ultricies eleifend. Aliquam sollicitudin ligula eget sem aliquam hendrerit. Phasellus nec libero vitae magna iaculis fermentum non a ipsum. Mauris quis elit felis, at aliquam purus. Vivamus sit amet augue commodo orci commodo molestie eget sed eros. Praesent quis nisl id erat tincidunt pellentesque quis id dolor. Nunc sed magna sem, at fermentum sapien. Duis ante arcu, mollis in hendrerit et, mattis vel dui. In accumsan, dolor sit amet consequat adipiscing, tellus enim accumsan arcu, vel ultrices lorem quam eu metus. In vel lorem massa.</p>
  <p class="justifier">Integer sed risus metus, ullamcorper blandit ante. Curabitur non nulla quam, in eleifend arcu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse potenti. Nulla non massa tortor. Duis pretium lorem felis. Donec congue congue dui ac viverra. Morbi pulvinar metus id eros auctor vel vehicula lectus rhoncus. Nunc sem neque, mattis quis tempus quis, dignissim vitae nibh. Proin sed ante diam, quis ultricies elit. Aenean scelerisque risus eget tellus fringilla scelerisque. Phasellus risus ante, viverra ut convallis in, lacinia at lacus. Curabitur tristique eros sit amet dolor ultrices at fringilla mauris lacinia. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nullam vel nunc non risus consectetur consectetur. Pellentesque eu laoreet nulla.</p>
  <p class="justifier">Curabitur pellentesque, arcu quis pretium fermentum, est eros consequat augue, ut consequat ante tortor vel sapien. Donec id leo ligula. Quisque erat massa, porttitor imperdiet accumsan ac, vulputate ut purus. Aenean at diam a lacus congue ultrices. Ut volutpat placerat suscipit. Proin aliquam orci ligula, a malesuada libero. Vestibulum porta, risus eu semper viverra, magna erat luctus quam, eget ornare lacus enim accumsan justo. Duis nec mauris orci, eget congue lectus. Vivamus ut ligula non nisl feugiat gravida. Proin auctor pharetra ligula at ultricies. Donec porttitor lacus sit amet nisi rhoncus a varius tortor dapibus. Etiam odio risus, ultricies non rhoncus nec, rutrum sed ipsum. Proin id convallis velit. Integer lobortis elit et lacus fringilla at pretium nulla blandit. Sed mollis leo et urna fermentum eget lobortis diam viverra. Morbi lobortis malesuada libero sit amet congue. Nulla velit lorem, pulvinar sed blandit vel, venenatis eget quam. Nulla convallis massa suscipit lacus facilisis ac malesuada turpis rutrum. Fusce vitae magna ligula. </p>
  <p>&nbsp; </p>
</div>
